apiVersion: 1
datasources:
  - name: Cassandra
    type: hadesarchitect-cassandra-datasource
    uid: ffll2f3hp4em8f
    access: proxy
    url: cassandra:9042
    isDefault: true
    editable: false
    jsonData:
      keyspace: cryptopulse
      consistency: ONE
      user: cassandra
    secureJsonData:
      password: cassandra
