apiVersion: 1
datasources:
  - name: Cassandra
    type: hadesarchitect-cassandra-datasource
    uid: cassandra-datasource
    access: proxy
    url: "cassandra:9042"
    jsonData:
      keyspace: cryptopulse
      consistency: LOCAL_ONE
    version: 2
    editable: true
